create_clock -period 10.000 -name clk -waveform {0.000 5.000} [get_ports clk]
set_input_delay -clock [get_clocks clk] -min -add_delay 0.400 [get_ports reset_n]
set_input_delay -clock [get_clocks clk] -max -add_delay 0.400 [get_ports reset_n]

set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property PACKAGE_PIN R2 [get_ports reset_n]
set_property IOSTANDARD LVCMOS33 [get_ports reset_n]
set_property IOSTANDARD LVCMOS33 [get_ports {OUTPUT_MAX[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OUTPUT_MAX[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OUTPUT_MAX[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OUTPUT_MAX[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OUTPUT_MAX[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OUTPUT_MAX[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OUTPUT_MAX[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OUTPUT_MAX[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OUTPUT_MAX[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OUTPUT_MAX[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OUTPUT_MAX[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OUTPUT_MAX[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OUTPUT_MAX[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OUTPUT_MAX[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OUTPUT_MAX[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OUTPUT_MAX[0]}]
set_property PACKAGE_PIN L1 [get_ports {OUTPUT_MAX[15]}]
set_property PACKAGE_PIN P1 [get_ports {OUTPUT_MAX[14]}]
set_property PACKAGE_PIN N3 [get_ports {OUTPUT_MAX[13]}]
set_property PACKAGE_PIN P3 [get_ports {OUTPUT_MAX[12]}]
set_property PACKAGE_PIN U3 [get_ports {OUTPUT_MAX[11]}]
set_property PACKAGE_PIN W3 [get_ports {OUTPUT_MAX[10]}]
set_property PACKAGE_PIN V3 [get_ports {OUTPUT_MAX[9]}]
set_property PACKAGE_PIN V13 [get_ports {OUTPUT_MAX[8]}]
set_property PACKAGE_PIN V14 [get_ports {OUTPUT_MAX[7]}]
set_property PACKAGE_PIN U14 [get_ports {OUTPUT_MAX[6]}]
set_property PACKAGE_PIN U15 [get_ports {OUTPUT_MAX[5]}]
set_property PACKAGE_PIN W18 [get_ports {OUTPUT_MAX[4]}]
set_property PACKAGE_PIN V19 [get_ports {OUTPUT_MAX[3]}]
set_property PACKAGE_PIN U19 [get_ports {OUTPUT_MAX[2]}]
set_property PACKAGE_PIN E19 [get_ports {OUTPUT_MAX[1]}]
set_property PACKAGE_PIN U16 [get_ports {OUTPUT_MAX[0]}]

